### ISSUE TITLE
Closing not working as excepted

### ISSUE THREAD

**Issue by dabuchera** [holepunchto/bare-readline#2]
Hi
The `close()` function is [implemented](https://github.com/holepunchto/bare-readline/blob/00b148ce8750336b4ccff9d3aeaa519026182c66/index.js#L47), but in my opinion it does not have the desired behavior.

It looks as if an event listener is still running. This can be tested with the following [app](https://github.com/holepunchto/pear-docs/blob/33dd6e8c8ba6916d83a07e6c1fa188c0ecb19ece/guide/making-a-pear-terminal-app.md). 
In my prototype I would like to use multiple instances of:
```
const rl = readline.createInterface({
    input: new tty.ReadStream(0),
    output: new tty.WriteStream(1),
  })
```
to switch between a chat module and the main CLI.

**Comment by dabuchera** [comment]
Another possibility would be to use `pause() `or `resume() `which are inherited from the `Readable `[class](https://github.com/holepunchto/bare-readline/blob/00b148ce8750336b4ccff9d3aeaa519026182c66/index.js#L9).

**Comment by kasperisager** [comment]
What exactly do you mean by "it looks as if an event listener is still running"?

**Comment by dabuchera** [comment]
Haha sry for the weak description. 
But what I meant is that when I close the interface `rl.close()`, an input from the terminal is still running and is also processed via `_onkey`.

**Comment by dabuchera** [comment]
Tried to replicate the problems below
```
import tty from 'bare-tty'
import readline from 'bare-readline'

const rl = readline.createInterface({
  input: new tty.ReadStream(0),
  output: new tty.WriteStream(1),
})

/* When using MODE_RAW the beavior is optimal, but Ctrl+C is not working
Solution for the is to add process.exit() in the /bare-readline

rl.close() is not working */
rl.input.setMode(tty.constants.MODE_RAW)

/* When using MODE_IO Ctrl+C is working, but not Ctrl+D
But the beavior is not optimal with the input repeating randomly
rl.close() is not working */
// rl.input.setMode(tty.constants.MODE_NORMAL)

/* When using MODE_IO Ctrl+C is working, but not Ctrl+D
But the beavior is not optimal with the input repeating randomly
rl.close() is not working */
// rl.input.setMode(tty.constants.MODE_IO)

rl.on('data', line => {
  if (line === 'exit') {
    rl.close()
    return
  }
  console.log('\r\n' + line)
  rl.prompt()
}).prompt()

```

**Comment by kasperisager** [comment]
Ah, I see the issue! The module wasn't detaching from `input` on `readline.close()` which has been fixed in https://github.com/holepunchto/bare-readline/commit/40045ce0e9504c6fc3794cb45b36ab7515175bba.

**Comment by covert-oddity** [comment]
I am seeing the same issue with latest package 1.0.9

```javascript
const readline = require('readline')
const process = require('process')

function main() {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
        prompt: 'QVAC> ',
        terminal: true
      })

    rl.on('data', (line) => {
        if (line.toLowerCase() === 'exit') {
            console.log('exiting')
            rl.close()
            return
        }
        console.log('line', line)
    })
}

main()
```

Bare doesn't exit after rl.close()

**Comment by kasperisager** [comment]
You're not closing `stdin` and `stdout`.
